### PR TITLE
null safety migration

### PR DESCRIPTION
**Pull request by abbasghomi**
- null safety migration
- package and sample projects refactored

### CODE REVIEW

**Comment by abbasghomi** [comment]
@biocarl Please review

**Comment by aagarcia** [comment]
@biocarl when integrate this update to the pub.dev. I need use this update with null safety. Please.

**Comment by abbasghomi** [comment]
@biocarl  @mgallo Please review

**Comment by mgallo** [comment]
Hi @abbasghomi, I'm sorry but the maintainer of the package is @biocarl, I only contributed to the package with another PR and cannot merge your PR.
In the meantime, if you need to use it in your app, you can use your fork by referencing it in pubspec.yaml as described here: https://dart.dev/tools/pub/dependencies#git-packages (I know this is not a proper solution, but can be a workaround while you're waiting for the merge).

**Comment by alphamikle** [comment]
Hello, @biocarl, can you accept this PR?

**Comment by haucky** [comment]
sorry for letting you wait for so long! :-)
https://pub.dev/packages/drawing_animation -> published ✅

**Pull request merged**
